# Generated by Django 5.2.17 on 2026-08-24 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "operacao",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Alteração"),
                            ("DELETE", "Exclusão"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tabela", models.CharField(db_index=True, max_length=100)),
                ("registro_id", models.CharField(db_index=True, max_length=64)),
                ("campo", models.CharField(blank=True, max_length=100)),
                ("valor_anterior", models.TextField(blank=True)),
                ("valor_novo", models.TextField(blank=True)),
                ("justificativa", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoria",
                "verbose_name_plural": "auditoria",
                "ordering": ("-data_hora", "-id"),
            },
        ),
    ]
