# Generated by Django 5.2.17 on 2026-08-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="perfil",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("ATENDENTE", "Atendente"),
                    ("COORDENACAO", "Coordenação"),
                    ("CONSULTA", "Consulta"),
                    ("RECEPCAO", "Recepção (Senhas)"),
                ],
                default="ATENDENTE",
                max_length=20,
                verbose_name="Perfil",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="perfil",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("ATENDENTE", "Atendente"),
                    ("COORDENACAO", "Coordenação"),
                    ("CONSULTA", "Consulta"),
                    ("RECEPCAO", "Recepção (Senhas)"),
                ],
                default="ATENDENTE",
                max_length=20,
                verbose_name="Perfil",
            ),
        ),
    ]
