# Generated by Django 5.2.17 on 2026-08-12 12:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalVeiculo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True,
                        help_text="Nome usado na agenda e no mapa (ex.: CARRO 1, AMBULÂNCIA 2).",
                        max_length=40,
                        verbose_name="Identificação",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("UTILITARIO", "Carro / Utilitário"),
                            ("AMBULANCIA", "Ambulância"),
                            ("MICRO", "Micro-ônibus"),
                            ("VAN", "Van"),
                            ("OUTRO", "Outro"),
                        ],
                        default="UTILITARIO",
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "placa",
                    models.CharField(blank=True, max_length=10, verbose_name="Placa"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Observações"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Veículo",
                "verbose_name_plural": "historical Veículos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome usado na agenda e no mapa (ex.: CARRO 1, AMBULÂNCIA 2).",
                        max_length=40,
                        unique=True,
                        verbose_name="Identificação",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("UTILITARIO", "Carro / Utilitário"),
                            ("AMBULANCIA", "Ambulância"),
                            ("MICRO", "Micro-ônibus"),
                            ("VAN", "Van"),
                            ("OUTRO", "Outro"),
                        ],
                        default="UTILITARIO",
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "placa",
                    models.CharField(blank=True, max_length=10, verbose_name="Placa"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Observações"
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["nome"],
            },
        ),
    ]
