# Generated by Django 5.2.17 on 2026-08-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_ibge",
                    models.CharField(
                        max_length=7, unique=True, verbose_name="Código IBGE"
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                ("uf", models.CharField(default="MG", max_length=2, verbose_name="UF")),
            ],
            options={
                "verbose_name": "Município",
                "verbose_name_plural": "Municípios",
                "ordering": ["nome"],
            },
        ),
    ]
