# Generated by Django 5.2.17 on 2026-08-06 16:36

import apps.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPaciente",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome completo"),
                ),
                (
                    "cns",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="15 dígitos. Usado no BPA e para evitar duplicidade.",
                        max_length=15,
                        null=True,
                        validators=[apps.core.validators.validar_cns],
                        verbose_name="Cartão SUS (CNS)",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=11,
                        null=True,
                        validators=[apps.core.validators.validar_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de nascimento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "raca_cor",
                    models.CharField(
                        choices=[
                            ("01", "Branca"),
                            ("02", "Preta"),
                            ("03", "Parda"),
                            ("04", "Amarela"),
                            ("05", "Indígena"),
                            ("99", "Sem informação"),
                        ],
                        default="99",
                        max_length=2,
                        verbose_name="Raça/Cor",
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        blank=True,
                        help_text="Quando indígena (BPA).",
                        max_length=80,
                        verbose_name="Etnia",
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        default="Brasileira",
                        max_length=60,
                        verbose_name="Nacionalidade",
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=8, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=80, verbose_name="Bairro"),
                ),
                (
                    "telefone_principal",
                    models.CharField(max_length=20, verbose_name="Telefone principal"),
                ),
                (
                    "telefone_secundario",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone secundário"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.municipio",
                        verbose_name="Município",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Paciente",
                "verbose_name_plural": "historical Pacientes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome completo"),
                ),
                (
                    "cns",
                    models.CharField(
                        blank=True,
                        help_text="15 dígitos. Usado no BPA e para evitar duplicidade.",
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[apps.core.validators.validar_cns],
                        verbose_name="Cartão SUS (CNS)",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[apps.core.validators.validar_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de nascimento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "raca_cor",
                    models.CharField(
                        choices=[
                            ("01", "Branca"),
                            ("02", "Preta"),
                            ("03", "Parda"),
                            ("04", "Amarela"),
                            ("05", "Indígena"),
                            ("99", "Sem informação"),
                        ],
                        default="99",
                        max_length=2,
                        verbose_name="Raça/Cor",
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        blank=True,
                        help_text="Quando indígena (BPA).",
                        max_length=80,
                        verbose_name="Etnia",
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        default="Brasileira",
                        max_length=60,
                        verbose_name="Nacionalidade",
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=8, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=80, verbose_name="Bairro"),
                ),
                (
                    "telefone_principal",
                    models.CharField(max_length=20, verbose_name="Telefone principal"),
                ),
                (
                    "telefone_secundario",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone secundário"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pacientes",
                        to="core.municipio",
                        verbose_name="Município",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["nome"], name="pacientes_p_nome_32514d_idx"),
                    models.Index(fields=["cpf"], name="pacientes_p_cpf_be7b38_idx"),
                    models.Index(fields=["cns"], name="pacientes_p_cns_88b6d7_idx"),
                ],
            },
        ),
    ]
