# Generated by Django 5.2.17 on 2026-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpaciente",
            name="sexo",
            field=models.CharField(
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("N", "Não informado"),
                ],
                max_length=1,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="sexo",
            field=models.CharField(
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("N", "Não informado"),
                ],
                max_length=1,
                verbose_name="Sexo",
            ),
        ),
    ]
