# Generated by Django 5.2.17 on 2026-08-06 16:53

import apps.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinos", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAgendamento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "acompanhante",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Acompanhante"
                    ),
                ),
                (
                    "contato",
                    models.CharField(blank=True, max_length=40, verbose_name="Contato"),
                ),
                (
                    "data",
                    models.DateField(
                        validators=[apps.core.validators.validar_dia_util],
                        verbose_name="Data",
                    ),
                ),
                (
                    "horario",
                    models.TimeField(
                        validators=[apps.core.validators.validar_horario_agenda],
                        verbose_name="Horário",
                    ),
                ),
                (
                    "local_consulta",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Local da consulta"
                    ),
                ),
                (
                    "procedimento",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Procedimento"
                    ),
                ),
                (
                    "tipo_veiculo",
                    models.CharField(
                        blank=True,
                        help_text="Preenchimento livre (pode mudar na hora da viagem).",
                        max_length=60,
                        verbose_name="Tipo de veículo",
                    ),
                ),
                (
                    "local_embarque",
                    models.CharField(
                        blank=True,
                        help_text="Preenchimento livre.",
                        max_length=150,
                        verbose_name="Local de embarque",
                    ),
                ),
                (
                    "hora_embarque",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de embarque"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADO", "Agendado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EM_VIAGEM", "Em viagem"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                            ("FALTOU", "Faltou"),
                        ],
                        default="AGENDADO",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confirmado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmado em"
                    ),
                ),
                (
                    "embarque",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EMBARCOU", "Embarcou"),
                            ("NAO_EMBARCOU", "Não embarcou"),
                        ],
                        default="PENDENTE",
                        max_length=12,
                        verbose_name="Embarque",
                    ),
                ),
                (
                    "hora_embarque_real",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Embarque realizado às"
                    ),
                ),
                (
                    "hora_desembarque_real",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Desembarque às"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="destinos.destino",
                        verbose_name="Destino",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Agendamento",
                "verbose_name_plural": "historical Agendamentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "acompanhante",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Acompanhante"
                    ),
                ),
                (
                    "contato",
                    models.CharField(blank=True, max_length=40, verbose_name="Contato"),
                ),
                (
                    "data",
                    models.DateField(
                        validators=[apps.core.validators.validar_dia_util],
                        verbose_name="Data",
                    ),
                ),
                (
                    "horario",
                    models.TimeField(
                        validators=[apps.core.validators.validar_horario_agenda],
                        verbose_name="Horário",
                    ),
                ),
                (
                    "local_consulta",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Local da consulta"
                    ),
                ),
                (
                    "procedimento",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Procedimento"
                    ),
                ),
                (
                    "tipo_veiculo",
                    models.CharField(
                        blank=True,
                        help_text="Preenchimento livre (pode mudar na hora da viagem).",
                        max_length=60,
                        verbose_name="Tipo de veículo",
                    ),
                ),
                (
                    "local_embarque",
                    models.CharField(
                        blank=True,
                        help_text="Preenchimento livre.",
                        max_length=150,
                        verbose_name="Local de embarque",
                    ),
                ),
                (
                    "hora_embarque",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de embarque"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADO", "Agendado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EM_VIAGEM", "Em viagem"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                            ("FALTOU", "Faltou"),
                        ],
                        default="AGENDADO",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confirmado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmado em"
                    ),
                ),
                (
                    "embarque",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EMBARCOU", "Embarcou"),
                            ("NAO_EMBARCOU", "Não embarcou"),
                        ],
                        default="PENDENTE",
                        max_length=12,
                        verbose_name="Embarque",
                    ),
                ),
                (
                    "hora_embarque_real",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Embarque realizado às"
                    ),
                ),
                (
                    "hora_desembarque_real",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Desembarque às"
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos",
                        to="destinos.destino",
                        verbose_name="Destino",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["data", "horario"],
                "indexes": [
                    models.Index(
                        fields=["data", "horario"], name="agendamento_data_e6ff48_idx"
                    ),
                    models.Index(
                        fields=["status"], name="agendamento_status_24d1a6_idx"
                    ),
                ],
            },
        ),
    ]
