# Generated by Django 5.2.17 on 2026-08-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="veiculo",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecione o veículo. Pode ser trocado na hora da viagem.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="veiculos.veiculo",
                verbose_name="Veículo",
            ),
        ),
        migrations.AddField(
            model_name="historicalagendamento",
            name="veiculo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Selecione o veículo. Pode ser trocado na hora da viagem.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="veiculos.veiculo",
                verbose_name="Veículo",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="tipo_veiculo",
            field=models.CharField(
                blank=True,
                help_text="Opcional. Observação livre sobre o veículo, se necessário.",
                max_length=60,
                verbose_name="Complemento do veículo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalagendamento",
            name="tipo_veiculo",
            field=models.CharField(
                blank=True,
                help_text="Opcional. Observação livre sobre o veículo, se necessário.",
                max_length=60,
                verbose_name="Complemento do veículo",
            ),
        ),
    ]
