# Generated by Django 5.2.17 on 2026-09-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agendamentos",
            "0002_agendamento_veiculo_historicalagendamento_veiculo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="acompanhante_cpf",
            field=models.CharField(
                blank=True, max_length=11, verbose_name="CPF do acompanhante"
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="km_rodado",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quilômetros rodados na viagem (pode ser preenchido no retorno).",
                null=True,
                verbose_name="KM rodado",
            ),
        ),
        migrations.AddField(
            model_name="historicalagendamento",
            name="acompanhante_cpf",
            field=models.CharField(
                blank=True, max_length=11, verbose_name="CPF do acompanhante"
            ),
        ),
        migrations.AddField(
            model_name="historicalagendamento",
            name="km_rodado",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quilômetros rodados na viagem (pode ser preenchido no retorno).",
                null=True,
                verbose_name="KM rodado",
            ),
        ),
    ]
