# Generated by Django 5.2.17 on 2026-08-24 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_inscricao",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("RECEBIDA", "Inscrição recebida"),
                            ("EM_ANALISE", "Em análise"),
                            ("PENDENCIA", "Pendência"),
                            ("DOC_VALIDADA", "Documentação validada"),
                            ("APTO", "Apto"),
                            ("INAPTO", "Não apto"),
                            ("INDEFERIDO", "Indeferido"),
                            ("HOMOLOGADO", "Homologado"),
                            ("CLASSIFICADO", "Classificado"),
                            ("ENCAMINHADO_CAIXA", "Encaminhado à CAIXA"),
                        ],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("endereco", models.CharField(blank=True, max_length=200)),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("complemento", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("cep", models.CharField(blank=True, max_length=9)),
                ("data_referencia", models.DateField(blank=True, null=True)),
                ("habitacao_precaria_ou_risco", models.BooleanField(default=False)),
                ("matricula_comprovada", models.BooleanField(default=False)),
                (
                    "aluguel_mes_1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "aluguel_mes_2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "aluguel_mes_3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "aluguel_cedido",
                    models.BooleanField(
                        default=False, verbose_name="imóvel cedido/emprestado"
                    ),
                ),
                (
                    "renda_bruta_computavel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "aluguel_medio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "renda_per_capita",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "percentual_aluguel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("pontos_legais", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pontos_complementares",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "pontuacao_total",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("data_finalizacao", models.DateTimeField(blank=True, null=True)),
                ("bloqueada", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "inscrição",
                "verbose_name_plural": "inscrições",
                "ordering": ("-data_inscricao",),
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="data de nascimento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino")],
                        default="F",
                        max_length=1,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOLTEIRO", "Solteiro(a)"),
                            ("CASADO", "Casado(a)"),
                            ("SEPARADO", "Separado(a)"),
                            ("DIVORCIADO", "Divorciado(a)"),
                            ("VIUVO", "Viúvo(a)"),
                            ("UNIAO_ESTAVEL", "União estável"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pcd",
                    models.BooleanField(
                        default=False, verbose_name="pessoa com deficiência"
                    ),
                ),
                (
                    "brasileiro",
                    models.BooleanField(
                        default=True, verbose_name="brasileiro(a) nato/naturalizado(a)"
                    ),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("obrigatorio", models.BooleanField(default=True)),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("RECEBIDO", "Recebido"),
                            ("EM_ANALISE", "Em análise"),
                            ("APROVADO", "Aprovado"),
                            ("REJEITADO", "Rejeitado"),
                            ("SUBSTITUICAO", "Substituição solicitada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                ("data_conferencia", models.DateTimeField(blank=True, null=True)),
                (
                    "conferido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_conferidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="cadastro.inscricao",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="cadastro.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
            },
        ),
        migrations.CreateModel(
            name="CriterioComplementar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "renda_per_capita",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("pontos_renda", models.PositiveIntegerField(default=0)),
                (
                    "aluguel_medio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("pontos_aluguel", models.PositiveIntegerField(default=0)),
                (
                    "inscricao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterio_complementar",
                        to="cadastro.inscricao",
                    ),
                ),
            ],
            options={
                "verbose_name": "critério complementar",
                "verbose_name_plural": "critérios complementares",
            },
        ),
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posicao", models.PositiveIntegerField(blank=True, null=True)),
                ("pontuacao", models.PositiveIntegerField(db_index=True, default=0)),
                ("dependentes_ate_12", models.PositiveIntegerField(default=0)),
                ("idosos", models.PositiveIntegerField(default=0)),
                ("empate_pendente_sorteio", models.BooleanField(default=False)),
                (
                    "sorteio_ata",
                    models.FileField(
                        blank=True, null=True, upload_to="sorteios/%Y/%m/"
                    ),
                ),
                (
                    "inscricao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacao",
                        to="cadastro.inscricao",
                    ),
                ),
            ],
            options={
                "verbose_name": "classificação",
                "verbose_name_plural": "classificações",
                "ordering": ("posicao",),
            },
        ),
        migrations.CreateModel(
            name="MembroNucleo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parentesco",
                    models.CharField(
                        choices=[
                            ("REQUERENTE", "Requerente"),
                            ("CONJUGE", "Cônjuge"),
                            ("COMPANHEIRO", "Companheiro(a)"),
                            ("FILHO", "Filho(a)"),
                            ("ENTEADO", "Enteado(a)"),
                            ("PAI", "Pai"),
                            ("MAE", "Mãe"),
                            ("PADRASTO", "Padrasto"),
                            ("MADRASTA", "Madrasta"),
                            ("IRMAO", "Irmão(ã)"),
                            ("TUTELADO", "Menor sob tutela"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dependente", models.BooleanField(default=False)),
                (
                    "arrimo",
                    models.BooleanField(default=False, verbose_name="arrimo do núcleo"),
                ),
                ("considerado_apuracao_renda", models.BooleanField(default=True)),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="cadastro.inscricao",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacoes",
                        to="cadastro.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "membro do núcleo",
                "verbose_name_plural": "membros do núcleo",
            },
        ),
        migrations.AddField(
            model_name="inscricao",
            name="requerente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscricoes_como_requerente",
                to="cadastro.pessoa",
            ),
        ),
        migrations.CreateModel(
            name="Renda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FORMAL", "Emprego formal"),
                            ("INFORMAL", "Trabalho informal"),
                            ("AUTONOMO", "Autônomo"),
                            ("APOSENTADORIA", "Aposentadoria"),
                            ("PENSAO", "Pensão"),
                            ("BENEFICIO", "Benefício"),
                            ("OUTRA", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "computavel",
                    models.BooleanField(
                        default=True, verbose_name="computável para enquadramento"
                    ),
                ),
                (
                    "competencia",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="competência (MM/AAAA)"
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendas",
                        to="cadastro.membronucleo",
                    ),
                ),
            ],
            options={
                "verbose_name": "renda",
                "verbose_name_plural": "rendas",
            },
        ),
        migrations.CreateModel(
            name="CriterioLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inciso",
                    models.CharField(
                        choices=[
                            ("CL_I", "I — Habitação precária/risco ou acessibilidade"),
                            ("CL_II", "II — Crianças 0–12 com matrícula"),
                            ("CL_III", "III — Arrimo mulher ou idoso"),
                            ("CL_IV", "IV — Renda ≤ R$ 4.863,00"),
                        ],
                        max_length=6,
                    ),
                ),
                ("atendido", models.BooleanField(default=False)),
                ("comprovado", models.BooleanField(default=False)),
                ("pontos", models.PositiveIntegerField(default=0)),
                (
                    "documento_comprova",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cadastro.documento",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios_legais",
                        to="cadastro.inscricao",
                    ),
                ),
            ],
            options={
                "verbose_name": "critério legal",
                "verbose_name_plural": "critérios legais",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inscricao", "inciso"),
                        name="inciso_unico_por_inscricao",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="membronucleo",
            constraint=models.UniqueConstraint(
                fields=("inscricao", "pessoa"), name="pessoa_unica_por_inscricao"
            ),
        ),
    ]
