# Generated by Django 5.2.17 on 2026-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="motivo_inaptidao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="nao_beneficiado_declarado",
            field=models.BooleanField(
                default=False, verbose_name="nunca beneficiado por prog. habitacional"
            ),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="nao_proprietario_declarado",
            field=models.BooleanField(
                default=False, verbose_name="não é proprietário de imóvel"
            ),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="residencia_5anos_comprovada",
            field=models.BooleanField(
                default=False, verbose_name="reside há ≥ 5 anos (comprovado)"
            ),
        ),
    ]
