# Generated by Django 5.2.17 on 2026-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0002_inscricao_motivo_inaptidao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="protocolo",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
