# Generated by Django 5.2.17 on 2026-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_inscricao_protocolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="uf",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
    ]
