# Generated by Django 5.2.17 on 2026-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0004_inscricao_cidade_inscricao_uf"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="ciencia_lgpd",
            field=models.BooleanField(
                default=False, verbose_name="declaração de ciência (LGPD)"
            ),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="ciencia_lgpd_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
