# Generated by Django 5.2.17 on 2026-08-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0005_inscricao_ciencia_lgpd_inscricao_ciencia_lgpd_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("RG", "RG"),
                    ("CPF", "CPF"),
                    ("CERT_CASAMENTO", "Certidão de Casamento"),
                    (
                        "CERT_CASAMENTO_DIVORCIO",
                        "Certidão de Casamento c/ averbação de divórcio",
                    ),
                    (
                        "CERT_CASAMENTO_OBITO",
                        "Certidão de Casamento c/ averbação de óbito",
                    ),
                    ("CERT_OBITO", "Certidão de Óbito"),
                    ("CERT_NASCIMENTO", "Certidão de Nascimento"),
                    ("UNIAO_ESTAVEL", "Escritura/Declaração de União Estável"),
                    (
                        "DECL_ESTADO_CIVIL",
                        "Declaração de não alteração do estado civil (Anexo IV)",
                    ),
                    ("COMP_ENDERECO", "Comprovante de endereço (água/energia)"),
                    (
                        "DECL_MORADIA",
                        "Declaração de moradia (alugado/cedido/emprestado)",
                    ),
                    ("CONTRATO_LOCACAO", "Contrato de locação assinado"),
                    ("RENDA_CONTRACHEQUE", "Renda — contracheque (3 últimos meses)"),
                    ("RENDA_EXTRATO", "Renda — extrato bancário/IR/pró-labore"),
                    (
                        "RENDA_INSS",
                        "Renda — extrato INSS/RPPS (aposentado/pensionista)",
                    ),
                    ("RES5_SAUDE", "Residência 5 anos — atenção básica de saúde"),
                    (
                        "RES5_CONCESSIONARIA",
                        "Residência 5 anos — água/energia (ininterrupto)",
                    ),
                    (
                        "RES5_ESCOLAR",
                        "Residência 5 anos — histórico/declaração escolar",
                    ),
                    ("RES5_CTPS", "Residência 5 anos — CTPS c/ contrato no município"),
                    ("RES5_OUTRO", "Residência 5 anos — outro documento oficial"),
                    ("ANEXO_II", "Declaração de Inscrição e Anuência (Anexo II)"),
                    ("ANEXO_III", "Declaração Negativa de Propriedade (Anexo III)"),
                    ("LAUDO_PCD", "Laudo médico de deficiência"),
                    (
                        "MORADIA_RISCO",
                        "Comprovação de moradia precária/risco (Defesa Civil/laudo)",
                    ),
                    ("CADUNICO", "Declaração do CadÚnico (mulher responsável)"),
                    ("OUTRO", "Outro (especificar na observação)"),
                ],
                max_length=100,
            ),
        ),
    ]
