# Generated by Django 5.2.17 on 2026-08-27 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0006_alter_documento_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="finalizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inscricoes_finalizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
