# Generated by Django 5.2.17 on 2026-08-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_inscricao_finalizado_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renda",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("FORMAL", "Emprego formal"),
                    ("INFORMAL", "Trabalho informal"),
                    ("AUTONOMO", "Autônomo"),
                    ("APOSENTADORIA", "Aposentadoria"),
                    ("PENSAO", "Pensão"),
                    ("BENEFICIO", "Benefício previdenciário/outro"),
                    ("BPC", "BPC/LOAS (não computável)"),
                    ("BOLSA_FAMILIA", "Bolsa Família (não computável)"),
                    ("SEGURO_DESEMPREGO", "Seguro-desemprego (não computável)"),
                    ("AUXILIO_DOENCA", "Auxílio-doença (não computável)"),
                    ("AUXILIO_ACIDENTE", "Auxílio-acidente (não computável)"),
                    ("OUTRA", "Outra"),
                ],
                max_length=20,
            ),
        ),
    ]
