# Generated by Django 5.2.17 on 2026-08-06 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Senha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField(verbose_name="Número")),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("CHAMADA", "Chamada"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="AGUARDANDO",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "guiche",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Guichê"
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Emitida em"),
                ),
                (
                    "chamada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Chamada em"
                    ),
                ),
                (
                    "finalizada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizada em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Senha",
                "verbose_name_plural": "Senhas",
                "ordering": ["-criada_em"],
                "indexes": [
                    models.Index(
                        fields=["data", "status"], name="senhas_senh_data_6e7873_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Painel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequencia", models.PositiveIntegerField(default=0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "senha_atual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="senhas.senha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Painel",
                "verbose_name_plural": "Painel",
            },
        ),
    ]
