# Generated by Django 5.2.17 on 2026-08-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senhas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="senha",
            name="senhas_senh_data_6e7873_idx",
        ),
        migrations.AddField(
            model_name="painel",
            name="tipo",
            field=models.CharField(
                default="TRANSPORTE", max_length=20, unique=True, verbose_name="Fila"
            ),
        ),
        migrations.AddField(
            model_name="senha",
            name="tipo",
            field=models.CharField(
                default="TRANSPORTE", max_length=20, verbose_name="Fila"
            ),
        ),
        migrations.AlterField(
            model_name="senha",
            name="guiche",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Sala"
            ),
        ),
        migrations.AddIndex(
            model_name="senha",
            index=models.Index(
                fields=["tipo", "data", "status"], name="senhas_senh_tipo_857f40_idx"
            ),
        ),
    ]
