# Generated by Django 5.2.17 on 2026-08-06 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario_nome",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Usuário"
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FALHOU", "Tentativa de login falhou"),
                            ("BLOQUEIO", "Acesso bloqueado (tentativas)"),
                            ("EXPORTACAO", "Exportação de relatório"),
                            ("IMPRESSAO", "Impressão de documento"),
                            ("BACKUP", "Backup do banco de dados"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "detalhe",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Detalhe"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/hora"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoria",
                "verbose_name_plural": "Registros de auditoria",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["acao", "criado_em"], name="auditoria_r_acao_2383ca_idx"
                    )
                ],
            },
        ),
    ]
