# Generated by Django 5.2.17 on 2026-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="acao",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("LOGIN_FALHOU", "Tentativa de login falhou"),
                    ("BLOQUEIO", "Acesso bloqueado (tentativas)"),
                    ("EXPORTACAO", "Exportação de relatório"),
                    ("IMPRESSAO", "Impressão de documento"),
                    ("BACKUP", "Backup do banco de dados"),
                    ("SENHA", "Alteração de senha"),
                ],
                max_length=20,
                verbose_name="Ação",
            ),
        ),
    ]
